### ISSUE TITLE
ERROR in   TypeError: __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by damianobarbati** [webpack-contrib/html-webpack-plugin#12]
I'm reporting a bug with `webpack-contrib/html-webpack-plugin`.
```
ERROR in   TypeError: __webpack_require__(...) is not a function
  - es6.regexp.replace.js?:2 eval
    [.]/[core-js]/modules/es6.regexp.replace.js?:2:90
```

Full repro here: https://github.com/damianobarbati/yarsk
To run just `yarn install` and `yarn build:dev` (which converts to a simple webpack build command).

Versions and infos:
```
imac:yarsk damz$ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v9.5.0
darwin 17.4.0
imac:yarsk damz$ npm --version
5.7.0
imac:yarsk damz$ npm ls webpack
yarsk@1.0.0 /Users/damz/Desktop/yarsk
`-- (empty)

imac:yarsk damz$ npm ls html-webpack-plugin
yarsk@1.0.0 /Users/damz/Desktop/yarsk
`-- html-webpack-plugin@2.30.1  invalid

npm ERR! invalid: html-webpack-plugin@2.30.1 /Users/damz/Desktop/yarsk/node_modules/html-webpack-plugin
```

**Comment by Graham42** [comment]
Thanks for the reproducible example. I was able to reproduce using the repo at commit https://github.com/damianobarbati/yarsk/commit/b551f1a0883fc8040e8025f5f5966d9a5deafa74 .

Your webpack version is `^4.0.0-beta.2` which is out of date. And you're missing `extract-text-webpack-plugin` which is another peer dependency. 

It looks like you may have solved this? (you commented in https://github.com/webpack/webpack/issues/6544#issuecomment-368023618)

**Comment by damianobarbati** [comment]
Yes @Graham42 sorry for the noise! It was a babel error actually but I was misled because it ended up into the html file: I really don't know how this happened since the error is a runtime one
